nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:5173'] # Autorise le frontend Vite en local
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/': # Applique la configuration CORS uniquement aux routes de l'API
            allow_origin: ['http://localhost:5173']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: ['Link']
            max_age: 3600